server:
  port: 8083


spring:
  application:
  name: spotify-to-kafka-service

spotify-to-kafka-service:
  spotify-keywords:
    - Bob Dylan
    - Paul Simon
    - Billie Eilish
    - Stevie Ray Vaughan
